# Generated by Django 3.2.8 on 2021-12-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triple',
            old_name='drug_name',
            new_name='drugname',
        ),
        migrations.AlterModelTable(
            name='drug',
            table='pd_drugs',
        ),
    ]
