# Generated by Django 3.2.8 on 2021-12-02 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0002_auto_20211202_0137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prescriber',
            table='pd_prescriber',
        ),
        migrations.AlterModelTable(
            name='state',
            table='pd_state',
        ),
        migrations.AlterModelTable(
            name='triple',
            table='pd_triple',
        ),
    ]
