# Generated by Django 3.2.8 on 2021-12-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0003_auto_20211202_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='drugid',
            field=models.IntegerField(default=0),
        ),
    ]
