# Generated by Django 3.2.8 on 2021-12-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0004_drug_drugid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='id',
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
