# Generated by Django 3.2.8 on 2021-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0005_auto_20211202_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='death',
            new_name='deaths',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_abv',
            new_name='stateabbrev',
        ),
        migrations.AddField(
            model_name='prescriber',
            name='npi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='state',
            table='pd_statedata',
        ),
    ]
