# Generated by Django 3.2.8 on 2021-12-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0006_auto_20211202_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AlterField(
            model_name='state',
            name='stateabbrev',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
