# Generated by Django 3.2.8 on 2021-12-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0007_auto_20211202_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triple',
            old_name='prescriber',
            new_name='prescriberid',
        ),
        migrations.AlterField(
            model_name='triple',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
