# Generated by Django 3.2.8 on 2021-12-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0008_auto_20211202_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriber',
            name='isopioidprescriber',
        ),
    ]
