# Generated by Django 3.2.8 on 2021-12-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0009_remove_prescriber_isopioidprescriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriber',
            name='isopioidprescriber',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
