# Generated by Django 3.2.8 on 2021-12-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0010_prescriber_isopioidprescriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriber',
            name='id',
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='npi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
