# Generated by Django 3.2.8 on 2021-12-02 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0011_auto_20211202_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='state',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='opioidapp.state'),
        ),
    ]
