# Generated by Django 3.2.8 on 2021-12-03 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0013_auto_20211202_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drugname',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='triple',
            name='drugname',
            field=models.ForeignKey(db_column='drugname', on_delete=django.db.models.deletion.CASCADE, to='opioidapp.drug', to_field='drugname'),
        ),
    ]
