# Generated by Django 3.2.8 on 2021-12-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opioidapp', '0016_prescriberonlyopioids'),
    ]

    operations = [
        migrations.CreateModel(
            name='highOpioids',
            fields=[
                ('prescriberid', models.IntegerField(primary_key=True, serialize=False)),
                ('pctopioids', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OverallPrescriptions',
            fields=[
                ('prescriberid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
